project:
  type: book

book:
  title: "World Bank SDMX Handbook"
  author: "Tony Fujs"
  date: "10/30/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - 00-the-whole-game.qmd
    - 01-dataflow-step-by-step-creation.qmd
    - 01-how-to-create-a-data-pipeline.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual

